<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net7.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="Interfaces\" />
    <Folder Include="Implementations\" />
    <Folder Include="DTOs\" />
    <Folder Include="Mappings\" />
    <Folder Include="Email\" />
    <Folder Include="FileStorage\" />
    <Folder Include="Validators\" />
  </ItemGroup>

</Project>
